###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mysql:
        image: "mysql:8.0"
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        working_dir: /application
        volumes:
            - "mysql-data:/var/lib/mysql"
            - ".:/application"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "3306:${DB_PORT}"

    webserver:
        image: "nginx:alpine"
        working_dir: /application
        volumes:
            - ".:/application"
            - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "${APP_PORT}:${APP_PORT}"

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - ".:/application"
            - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
            - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini"
        env_file:
            - .env

volumes:
    mysql-data:
