# Use an official Node.js runtime as a parent image
FROM node:20 AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular app
RUN npm run build --configuration=production

# Use an official Nginx image to serve the Angular app
FROM nginx:alpine

# Copy the custom Nginx configuration file
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy the Angular app build from the build stage to Nginx's default directory
COPY --from=build /app/dist/web-app/browser /usr/share/nginx/html

# Expose the port that Nginx is listening on
EXPOSE 80

# Start the Nginx server
CMD ["nginx", "-g", "daemon off;"]
