CREATE DATABASE rinno DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE rinno_dev DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER 'rinno'@'%' IDENTIFIED BY 'rinno';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER,REFERENCES,CREATE ROUTINE,ALTER ROUTINE,TRIGGER ON rinno.* TO 'rinno'@'%';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER,REFERENCES,CREATE ROUTINE,ALTER ROUTINE,TRIGGER ON rinno_dev.* TO 'rinno'@'%';
FLUSH PRIVILEGES;
